kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # This maps your localhost:80 to the kind node's port 80
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP